const products = [
    {
        name: "Asado Costilla x500grs.",
        category: "Frescos",
        id: 1,
        price: 750,
        stock: true,
        img: '../assets/img/ofertas/oferta1.jpg',
        shipping: true,
        offer: true,
    },
    {
        name: "Manzana Moño Azul x250grs.",
        category: "Frescos",
        id: 2,
        price: 400,
        stock: true,
        img: '../assets/img/ofertas/oferta2.jpg',
        shipping: true,
        offer: false,
    },
    {
        name: "Jamón Cocido Paladini x200grs",
        category: "Frescos",
        id: 3,
        price: 550,
        stock: true,
        img: '../assets/img/ofertas/oferta1.jpg',
        shipping: true,
        offer: false,
    },
    {
        name: "Falda x500grs.",
        category: "Frescos",
        id: 4,
        price: 400,
        stock: false,
        img: '../assets/img/ofertas/oferta1.jpg',
        shipping: true,
        offer: false,
    },
    {
        name: "Pan x500 grs",
        category: "Frescos",
        id: 5,
        price: 200,
        stock: true,
        img: '../assets/img/ofertas/oferta2.jpg',
        shipping: true,
        offer: false,
    },
    {
        name: "Vinagre de Alcohol Fischer x930cc.",
        category: "Almacen",
        id: 6,
        price: 270,
        stock: true,
        img: '../assets/img/ofertas/oferta3.jpg',
        shipping: true,
        offer: false,
    },
    {
        name: "Aceite Cañuelas x1,5lts.",
        category: "Almacen",
        id: 7,
        price: 850,
        stock: true,
        img: '../assets/img/ofertas/oferta4.jpg',
        shipping: true,
        offer: false,
    },
    {
        name: "Café Dolca Trad. x170grs.",
        category: "Almacen",
        id: 8,
        price: 840,
        stock: true,
        img: '../assets/img/ofertas/oferta3.jpg',
        shipping: true,
        offer: true,
    },
    {
        name: "Mayonesa Hellmans x475grs",
        category: "Almacen",
        id: 9,
        price: 250,
        stock: true,
        img: '../assets/img/ofertas/oferta4.jpg',
        shipping: true,
        offer: true,
    },
    {
        name: "Arroz Gallo Oro estuche x1kg.",
        category: "Almacen",
        id: 10,
        price: 320,
        stock: true,
        img: '../assets/img/ofertas/oferta3.jpg',
        shipping: true,
        offer: false,
    },
    {
        name: "Azucar Chango x1kg.",
        category: "Almacen",
        id: 11,
        price: 330,
        stock: false,
        img: '../assets/img/ofertas/oferta4.jpg',
        shipping: true,
        offer: false,
    },
    {
        name: "Termo Lumilagro",
        category: "Bazar",
        id: 12,
        price: 1430,
        stock: true,
        img: '../assets/img/ofertas/oferta5.jpg',
        shipping: true,
        offer: false,
    },
    {
        name: "Conservadora Cooleman",
        category: "Bazar",
        id: 13,
        price: 12430,
        stock: true,
        img: '../assets/img/ofertas/oferta6.jpg',
        shipping: true,
        offer: false,
    },
    {
        name: "Termo Plástico 3lts.",
        category: "Bazar",
        id: 14,
        price: 3420,
        stock: true,
        img: '../assets/img/ofertas/oferta5.jpg',
        shipping: true,
        offer: false,
    },
    {
        name: "Fernet Branca x1lts.",
        category: "Bebidas",
        id: 15,
        price: 2720,
        stock: true,
        img: '../assets/img/ofertas/oferta7.jpg',
        shipping: true,
        offer: false,
    },
    {
        name: "Cynar x750ml",
        category: "Bebidas",
        id: 16,
        price: 980,
        stock: true,
        img: '../assets/img/ofertas/oferta7.jpg',
        shipping: true,
        offer: false,
    },
    {
        name: "Cerveza Andes Origen Roja x473cc.",
        category: "Bebidas",
        id: 17,
        price: 270,
        stock: true,
        img: '../assets/img/ofertas/oferta8.jpg',
        shipping: true,
        offer: true,
    },
    {
        name: "Gaseosa Coca Cola Desc. x1,5lts.",
        category: "Bebidas",
        id: 18,
        price: 370,
        stock: true,
        img: '../assets/img/ofertas/oferta8.jpg',
        shipping: true,
        offer: false,
    },
    {
        name: "Gatorade Frutos Tropicales x500cc.",
        category: "Bebidas",
        id: 19,
        price: 265,
        stock: true,
        img: '../assets/img/ofertas/oferta8.jpg',
        shipping: true,
        offer: false,
    },
    {
        name: "Whisky Jonnie Walker Red Label x750cc.",
        category: "Bebidas",
        id: 20,
        price: 5169,
        stock: true,
        img: '../assets/img/ofertas/oferta7.jpg',
        shipping: true,
        offer: false,
    },
    {
        name: "Dogui Cachorros Car/Cer/Lec x8kg.",
        category: "Mascotas",
        id: 21,
        price: 4117,
        stock: true,
        img: '../assets/img/ofertas/oferta9.jpg',
        shipping: true,
        offer: false,
    },
    {
        name: "Gati Pollo/Zan/Espinaca x1kg.",
        category: "Mascotas",
        id: 22,
        price: 761,
        stock: true,
        img: '../assets/img/ofertas/oferta9.jpg',
        shipping: true,
        offer: true,
    },
    {
        name: "Limpiador Procenex Liq. Marina x900ml.",
        category: "Limpieza",
        id: 23,
        price: 185.90,
        stock: true,
        img: '../assets/img/ofertas/oferta10.jpg',
        shipping: true,
        offer: true,
    },
    {
        name: "Limpiador Pinoluz Liq. Pino x900ml.",
        category: "Limpieza",
        id: 24,
        price: 261.70,
        stock: true,
        img: '../assets/img/ofertas/oferta11.jpg',
        shipping: true,
        offer: false,
    },
    {
        name: "Quitaceras Suiza Autobrillo x850ml.",
        category: "Limpieza",
        id: 25,
        price: 1244.55,
        stock: true,
        img: '../assets/img/ofertas/oferta11.jpg',
        shipping: true,
        offer: false,
    },
    {
        name: "Desinf. Ayudin Aer. Frescura Matinal x332ml.",
        category: "Limpieza",
        id: 26,
        price: 195,
        stock: true,
        img: '../assets/img/ofertas/oferta11.jpg',
        shipping: true,
        offer: true,
    },
    {
        name: "Cif Limp. Vidrio D.P. x450ml",
        category: "Limpieza",
        id: 27,
        price: 170.80,
        stock: true,
        img: '../assets/img/ofertas/oferta12.jpg',
        shipping: true,
        offer: false,
    },
    {
        name: "Cif Limp. Baño Gatillo x500ml.",
        category: "Limpieza",
        id: 28,
        price: 391.45,
        stock: true,
        img: '../assets/img/ofertas/oferta12.jpg',
        shipping: true,
        offer: false,
    },
    {
        name: "Guantes Virulana Grande 8-8/12",
        category: "Limpieza",
        id: 29,
        price: 161.70,
        stock: true,
        img: '../assets/img/ofertas/oferta12.jpg',
        shipping: true,
        offer: true,
    },
    {
        name: "Bolsas Asurin 60x100 x10Unid. Rollo",
        category: "Limpieza",
        id: 30,
        price: 594,
        stock: true,
        img: '../assets/img/ofertas/oferta12.jpg',
        shipping: true,
        offer: false,
    },
    {
        name: "Dove Shampoo Prot/Cuidado Antib. x400ml.",
        category: "Perfumería",
        id: 31,
        price: 497,
        stock: true,
        img: '../assets/img/ofertas/oferta13.jpg',
        shipping: true,
        offer: false,
    },
    {
        name: "Dove Acond. Recon. Completa x200ml.",
        category: "Perfumería",
        id: 32,
        price: 337.70,
        stock: true,
        img: '../assets/img/ofertas/oferta14.jpg',
        shipping: true,
        offer: true,
    },
    {
        name: "Talco Veritas Clasico x180grs.",
        category: "Perfumería",
        id: 33,
        price: 528.10,
        stock: true,
        img: '../assets/img/ofertas/oferta13.jpg',
        shipping: true,
        offer: false,
    },
    {
        name: "Desod. Acqua Di Colbert x150ml",
        category: "Perfumería",
        id: 34,
        price: 640.85,
        stock: true,
        img: '../assets/img/ofertas/oferta14.jpg',
        shipping: true,
        offer: false,
    },
    {
        name: "Desod. Caro Cuore x123ml.",
        category: "Perfumería",
        id: 35,
        price: 656.95,
        stock: true,
        img: '../assets/img/ofertas/oferta13.jpg',
        shipping: true,
        offer: false,
    },
    {
        name: "Gel Villeneuve Post Solar C/A.V. 170grs.",
        category: "Perfumería",
        id: 36,
        price: 434,
        stock: false,
        img: '../assets/img/ofertas/oferta14.jpg',
        shipping: true,
        offer: false,
    },
    {
        name: "Pan Dulce Deubel C/Chips Choc x400grs.",
        category: "Otros",
        id: 37,
        price: 567.20,
        stock: true,
        img: '../assets/img/ofertas/oferta15.jpg',
        shipping: true,
        offer: true,
    },
    {
        name: "Pan Dulce Deubel C/Frutas x400grs.",
        category: "Otros",
        id: 38,
        price: 415,
        stock: true,
        img: '../assets/img/ofertas/oferta16.jpg',
        shipping: true,
        offer: true,
    },
    {
        name: "Budin Deubel Marmolado x250grs",
        category: "Otros",
        id: 39,
        price: 330.90,
        stock: true,
        img: '../assets/img/ofertas/oferta15.jpg',
        shipping: true,
        offer: true,
    },
    {
        name: "Budin Nevares Fantasia Limón x160grs.",
        category: "Otros",
        id: 40,
        price: 318.15,
        stock: true,
        img: '../assets/img/ofertas/oferta16.jpg',
        shipping: true,
        offer: true,
    },
    {
        name: "Turrón Grabich Crocante Maní x100grs.",
        category: "Otros",
        id: 41,
        price: 137,
        stock: false,
        img: '../assets/img/ofertas/oferta15.jpg',
        shipping: true,
        offer: true,
    },
    {
        name: "Almendras Georgalos Bañ. Choco. x100grs.",
        category: "Otros",
        id: 42,
        price: 692,
        stock: false,
        img: '../assets/img/ofertas/oferta16.jpg',
        shipping: true,
        offer: true,
    },
]

