const productos = [
    {
        nombre: "Asado Costilla x500grs.",
        categoria: "Frescos",
        id: 1,
        precio: 750,
        stock: true,
        imagen: '../assets/img/oferta1.jpg',
        envio: true,
        oferta: true,
    },
    {
        nombre: "Manzana Moño Azul x250grs.",
        categoria: "Frescos",
        id: 2,
        precio: 400,
        stock: true,
        imagen: '../assets/img/oferta2.jpg',
        envio: true,
        oferta: false,
    },
    {
        nombre: "Jamón Cocido Paladini x200grs",
        categoria: "Frescos",
        id: 3,
        precio: 550,
        stock: true,
        imagen: '../assets/img/oferta1.jpg',
        envio: true,
        oferta: false,
    },
    {
        nombre: "Falda x500grs.",
        categoria: "Frescos",
        id: 4,
        precio: 400,
        stock: false,
        imagen: '../assets/img/oferta1.jpg',
        envio: true,
        oferta: false,
    },
    {
        nombre: "Pan x500 grs",
        categoria: "Frescos",
        id: 5,
        precio: 200,
        stock: true,
        imagen: '../assets/img/oferta2.jpg',
        envio: true,
        oferta: false,
    },
    {
        nombre: "Vinagre de Alcohol Fischer x930cc.",
        categoria: "Almacen",
        id: 6,
        precio: 270,
        stock: true,
        imagen: '../assets/img/oferta3.jpg',
        envio: true,
        oferta: false,
    },
    {
        nombre: "Aceite Cañuelas x1,5lts.",
        categoria: "Almacen",
        id: 7,
        precio: 850,
        stock: true,
        imagen: '../assets/img/oferta4.jpg',
        envio: true,
        oferta: false,
    },
    {
        nombre: "Café Dolca Trad. x170grs.",
        categoria: "Almacen",
        id: 8,
        precio: 840,
        stock: true,
        imagen: '../assets/img/oferta3.jpg',
        envio: true,
        oferta: true,
    },
    {
        nombre: "Mayonesa Hellmans x475grs",
        categoria: "Almacen",
        id: 9,
        precio: 250,
        stock: true,
        imagen: '../assets/img/oferta4.jpg',
        envio: true,
        oferta: true,
    },
    {
        nombre: "Arroz Gallo Oro estuche x1kg.",
        categoria: "Almacen",
        id: 10,
        precio: 320,
        stock: true,
        imagen: '../assets/img/oferta3.jpg',
        envio: true,
        oferta: false,
    },
    {
        nombre: "Azucar Chango x1kg.",
        categoria: "Almacen",
        id: 11,
        precio: 330,
        stock: false,
        imagen: '../assets/img/oferta4.jpg',
        envio: true,
        oferta: false,
    },
    {
        nombre: "Termo Lumilagro",
        categoria: "Bazar",
        id: 12,
        precio: 1430,
        stock: true,
        imagen: '../assets/img/oferta5.jpg',
        envio: true,
        oferta: false,
    },
    {
        nombre: "Conservadora Cooleman",
        categoria: "Bazar",
        id: 13,
        precio: 12430,
        stock: true,
        imagen: '../assets/img/oferta6.jpg',
        envio: true,
        oferta: false,
    },
    {
        nombre: "Termo Plástico 3lts.",
        categoria: "Bazar",
        id: 14,
        precio: 3420,
        stock: true,
        imagen: '../assets/img/oferta5.jpg',
        envio: true,
        oferta: false,
    },
    {
        nombre: "Fernet Branca x1lts.",
        categoria: "Bebidas",
        id: 15,
        precio: 2720,
        stock: true,
        imagen: '../assets/img/oferta7.jpg',
        envio: true,
        oferta: false,
    },
    {
        nombre: "Cynar x750ml",
        categoria: "Bebidas",
        id: 16,
        precio: 980,
        stock: true,
        imagen: '../assets/img/oferta7.jpg',
        envio: true,
        oferta: false,
    },
    {
        nombre: "Cerveza Andes Origen Roja x473cc.",
        categoria: "Bebidas",
        id: 17,
        precio: 270,
        stock: true,
        imagen: '../assets/img/oferta8.jpg',
        envio: true,
        oferta: true,
    },
    {
        nombre: "Gaseosa Coca Cola Desc. x1,5lts.",
        categoria: "Bebidas",
        id: 18,
        precio: 370,
        stock: true,
        imagen: '../assets/img/oferta8.jpg',
        envio: true,
        oferta: false,
    },
    {
        nombre: "Gatorade Frutos Tropicales x500cc.",
        categoria: "Bebidas",
        id: 19,
        precio: 265,
        stock: true,
        imagen: '../assets/img/oferta8.jpg',
        envio: true,
        oferta: false,
    },
    {
        nombre: "Whisky Jonnie Walker Red Label x750cc.",
        categoria: "Bebidas",
        id: 20,
        precio: 5169,
        stock: true,
        imagen: '../assets/img/oferta7.jpg',
        envio: true,
        oferta: false,
    },
    {
        nombre: "Dogui Cachorros Car/Cer/Lec x8kg.",
        categoria: "Mascotas",
        id: 21,
        precio: 4117,
        stock: true,
        imagen: '../assets/img/oferta9.jpg',
        envio: true,
        oferta: false,
    },
    {
        nombre: "Gati Pollo/Zan/Espinaca x1kg.",
        categoria: "Mascotas",
        id: 22,
        precio: 761,
        stock: true,
        imagen: '../assets/img/oferta9.jpg',
        envio: true,
        oferta: true,
    },
    {
        nombre: "Limpiador Procenex Liq. Marina x900ml.",
        categoria: "Limpieza",
        id: 23,
        precio: 185.90,
        stock: true,
        imagen: '../assets/img/oferta10.jpg',
        envio: true,
        oferta: true,
    },
    {
        nombre: "Limpiador Pinoluz Liq. Pino x900ml.",
        categoria: "Limpieza",
        id: 24,
        precio: 261.70,
        stock: true,
        imagen: '../assets/img/oferta11.jpg',
        envio: true,
        oferta: false,
    },
    {
        nombre: "Quitaceras Suiza Autobrillo x850ml.",
        categoria: "Limpieza",
        id: 25,
        precio: 1244.55,
        stock: true,
        imagen: '../assets/img/oferta11.jpg',
        envio: true,
        oferta: false,
    },
    {
        nombre: "Desinf. Ayudin Aer. Frescura Matinal x332ml.",
        categoria: "Limpieza",
        id: 26,
        precio: 195,
        stock: true,
        imagen: '../assets/img/oferta11.jpg',
        envio: true,
        oferta: true,
    },
    {
        nombre: "Cif Limp. Vidrio D.P. x450ml",
        categoria: "Limpieza",
        id: 27,
        precio: 170.80,
        stock: true,
        imagen: '../assets/img/oferta12.jpg',
        envio: true,
        oferta: false,
    },
    {
        nombre: "Cif Limp. Baño Gatillo x500ml.",
        categoria: "Limpieza",
        id: 28,
        precio: 391.45,
        stock: true,
        imagen: '../assets/img/oferta12.jpg',
        envio: true,
        oferta: false,
    },
    {
        nombre: "Guantes Virulana Grande 8-8/12",
        categoria: "Limpieza",
        id: 29,
        precio: 161.70,
        stock: true,
        imagen: '../assets/img/oferta12.jpg',
        envio: true,
        oferta: true,
    },
    {
        nombre: "Bolsas Asurin 60x100 x10Unid. Rollo",
        categoria: "Limpieza",
        id: 30,
        precio: 594,
        stock: true,
        imagen: '../assets/img/oferta12.jpg',
        envio: true,
        oferta: false,
    },
    {
        nombre: "Dove Shampoo Prot/Cuidado Antib. x400ml.",
        categoria: "Perfumería",
        id: 31,
        precio: 497,
        stock: true,
        imagen: '../assets/img/oferta13.jpg',
        envio: true,
        oferta: false,
    },
    {
        nombre: "Dove Acond. Recon. Completa x200ml.",
        categoria: "Perfumería",
        id: 32,
        precio: 337.70,
        stock: true,
        imagen: '../assets/img/oferta14.jpg',
        envio: true,
        oferta: true,
    },
    {
        nombre: "Talco Veritas Clasico x180grs.",
        categoria: "Perfumería",
        id: 33,
        precio: 528.10,
        stock: true,
        imagen: '../assets/img/oferta13.jpg',
        envio: true,
        oferta: false,
    },
    {
        nombre: "Desod. Acqua Di Colbert x150ml",
        categoria: "Perfumería",
        id: 34,
        precio: 640.85,
        stock: true,
        imagen: '../assets/img/oferta14.jpg',
        envio: true,
        oferta: false,
    },
    {
        nombre: "Desod. Caro Cuore x123ml.",
        categoria: "Perfumería",
        id: 35,
        precio: 656.95,
        stock: true,
        imagen: '../assets/img/oferta13.jpg',
        envio: true,
        oferta: false,
    },
    {
        nombre: "Gel Villeneuve Post Solar C/A.V. 170grs.",
        categoria: "Perfumería",
        id: 36,
        precio: 434,
        stock: false,
        imagen: '../assets/img/oferta14.jpg',
        envio: true,
        oferta: false,
    },
    {
        nombre: "Pan Dulce Deubel C/Chips Choc x400grs.",
        categoria: "Otros",
        id: 37,
        precio: 567.20,
        stock: true,
        imagen: '../assets/img/oferta15.jpg',
        envio: true,
        oferta: true,
    },
    {
        nombre: "Pan Dulce Deubel C/Frutas x400grs.",
        categoria: "Otros",
        id: 38,
        precio: 415,
        stock: true,
        imagen: '../assets/img/oferta16.jpg',
        envio: true,
        oferta: true,
    },
    {
        nombre: "Budin Deubel Marmolado x250grs",
        categoria: "Otros",
        id: 39,
        precio: 330.90,
        stock: true,
        imagen: '../assets/img/oferta15.jpg',
        envio: true,
        oferta: true,
    },
    {
        nombre: "Budin Nevares Fantasia Limón x160grs.",
        categoria: "Otros",
        id: 40,
        precio: 318.15,
        stock: true,
        imagen: '../assets/img/oferta16.jpg',
        envio: true,
        oferta: true,
    },
    {
        nombre: "Turrón Grabich Crocante Maní x100grs.",
        categoria: "Otros",
        id: 41,
        precio: 137,
        stock: false,
        imagen: '../assets/img/oferta15.jpg',
        envio: true,
        oferta: true,
    },
    {
        nombre: "Almendras Georgalos Bañ. Choco. x100grs.",
        categoria: "Otros",
        id: 42,
        precio: 692,
        stock: false,
        imagen: '../assets/img/oferta16.jpg',
        envio: true,
        oferta: true,
    },
]

